-- ==========================================================================
-- RLS hardening, part 2 (Phase 2/3 sweep follow-up)
-- ==========================================================================
-- Two changes:
--
-- 1. suggestions: split compound ALL into SELECT + UPDATE only.
--    BEFORE: single policy "Users manage own suggestions" with cmd=ALL,
--            qual=with_check=(user_id = auth.uid()). In principle this lets
--            clients INSERT and DELETE their own suggestion rows.
--    AFTER : two policies — SELECT (read own) and UPDATE (mutate status of
--            own rows, e.g. accept/dismiss). No client INSERT, no client
--            DELETE. Suggestions are generated by the ai-generate and
--            intent-refresh edge functions under service_role (bypasses
--            RLS), and expired server-side by the same path. A client that
--            tries to INSERT a fake suggestion is now denied.
--    VERIFIED against packages/core/src/services/suggestions.service.ts:
--      getSuggestions        - SELECT only           (needs SELECT)
--      acceptSuggestion      - UPDATE status         (needs UPDATE)
--      dismissSuggestion     - UPDATE status         (needs UPDATE)
--      expireSuggestions     - UPDATE status (bulk)  (needs UPDATE; the
--                              SELECT call inside returns only rows this
--                              user already owns thanks to the SELECT
--                              policy, so the bulk path is user-scoped)
--    VERIFIED against supabase/functions/*/index.ts:
--      suggestions.insert appears only in ai-generate + intent-refresh,
--      both of which run under SUPABASE_SERVICE_ROLE_KEY (RLS bypass).
--
-- 2. momentum_availability: add missing UPDATE policy (fixes latent bug).
--    BEFORE: INSERT/SELECT/DELETE policies present; NO UPDATE policy. That
--            means every client-side `update()` call on this table is
--            silently blocked by RLS (0 rows affected, no error). The
--            momentum.service `tryWithFallback` legacy-schema ladder hid
--            this as a "primary update failed, try fallback" branch when
--            it was actually RLS denial.
--    AFTER : UPDATE is allowed when both the existing row and the post-
--            update row belong to the caller. Same invariant as the new
--            "plan_participants Update own status" policy from migration
--            20260416240000_rls_hardening.
-- ==========================================================================


-- --------------------------------------------------------------------------
-- 1. suggestions: split the compound ALL policy
-- --------------------------------------------------------------------------
-- Drop the catch-all; add per-command policies.
drop policy if exists "Users manage own suggestions" on public.suggestions;
drop policy if exists suggestions_select_own on public.suggestions;
drop policy if exists suggestions_update_own on public.suggestions;

create policy suggestions_select_own
  on public.suggestions for select
  to authenticated
  using (auth.uid() = user_id);

create policy suggestions_update_own
  on public.suggestions for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);


-- --------------------------------------------------------------------------
-- 2. momentum_availability: add missing UPDATE policy
-- --------------------------------------------------------------------------
-- Matches the shape of the other per-user-ownership UPDATE policies in the
-- hardening sweep: both qual (who can target the row) and with_check (what
-- the row looks like after) enforce user_id = auth.uid().
drop policy if exists "Users update own availability" on public.momentum_availability;
drop policy if exists momentum_availability_update_own on public.momentum_availability;

create policy momentum_availability_update_own
  on public.momentum_availability for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);


-- ==========================================================================
-- Verification (informational):
--
--   select tablename, policyname, cmd, qual, with_check
--   from pg_policies
--   where schemaname = 'public'
--     and tablename in ('suggestions', 'momentum_availability')
--   order by tablename, cmd, policyname;
--
-- Expected:
--   momentum_availability : INSERT, SELECT, UPDATE, DELETE policies present
--   suggestions           : SELECT + UPDATE only; no ALL / INSERT / DELETE
-- ==========================================================================
